server:
  port: 8090

kafka:
  brokers: 127.0.0.1:9092

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/skill_tracker_db?allowPublicKeyRetrieval=true&useSSL=false
    username: skill_tracker_user
    password: Password123

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
