server:
  port: 8090

kafka:
  brokers: 127.0.0.1:9092

spring:
  datasource:
    #url: jdbc:mysql://skill-tracker-db-instance.cnposghmoih7.us-east-1.rds.amazonaws.com:3306/skill_tracker_db
    username: skill_tracker_user
    password: Password123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
