server:
  port: 8091

spring:
  datasource:
    url: jdbc:mysql://skill-tracker-db-instance.cnposghmoih7.us-east-1.rds.amazonaws.com:3306/skill_tracker_db
    username: skill_tracker_user
    password: Password123
kafka:
  brokers: 127.0.0.1:9092

memcached:
  cache:
    servers: localhost:11211
    expirations: 3600
    operation-timeout: 3000